config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  resources :members 
  resources :charts

  get "import_members", :to => "members#import", :as => :import_members
  post "upload_members", :to => "members#upload", :as => :upload_members
  post "preview_members", :to => "members#preview", :as => :preview_members
  post "list_members", :to => "members#list", :as => :list_members
  get "preview_members", :to => "members#index"
end

app/models/member.rb
class Member < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def index
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index

  end

  def list
    members = Member
    records_total = members.count
    search_condition = params[:columns].map { |_, v| v[:search][:value] }
    MemberSystem::MemberFilesParser::COLUMNS.each_with_index do |col, idx|
      members = members.where("#{col} LIKE ?", "#{search_condition[idx]}%") unless search_condition[idx].empty?
    end
    records_filtered = members.count
    members = members.offset(params[:start]).limit(params[:length]).all

    res = {draw: params[:draw], recordsTotal: records_total, recordsFiltered: records_filtered, data: members.map { |m| m.attributes.symbolize_keys.except(:id, :created_at, :updated_at).values }}

    respond_to do |format|
      format.json { render json: res.to_json }
    end
  end

  def new
    @member = Member.new
  end

  def show
    @member = Member.find(params[:id])
  end

  def create
    permitted_params = params.require(:member).permit(:name, :email, :gender, :age)

    @member = Member.create(permitted_params)

    redirect_to member_path(@member)
  end

  def upload
    begin
      @records = MemberSystem::MemberFilesParser.parse(params[:member_files])
      
      @records.each { |r| Member.create(r) }
      
      flash[:message] = [:import_member_records_success, {:val => @records.length}]
    rescue
      flash[:error] = :import_member_records_failed
    end

    redirect_to members_path
  end

  def preview
    begin
      @records = MemberSystem::MemberFilesParser.parse(params[:member_files])
    rescue MemberSystem::ExceedMaximumRows
      flash[:error] = :exceed_maximum_rows
      redirect_to import_members_path
    rescue
      flash[:error] = :parsing_excel_failed 
      redirect_to import_members_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/charts/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%=I18n.t(:charts, scope: :generic)%></h1>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <%=I18n.t(:age_distribution, scope: :charts)%>
      </div>
      <div class="panel-body">
        <%= line_chart Member.group(:age).count, xtitle: I18n.t(:age, scope: :members), ytitle: I18n.t(:members, scope: :members) %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <%=I18n.t(:gender_distribution, scope: :charts)%>
      </div>
      <div class="panel-body">
        <%= pie_chart Member.group(:gender).count.map { |k, v| [I18n.t(k.downcase, scope: :charts), v] } %>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%=I18n.t(:dashboard, scope: :generic)%></h1>
  </div>
  <!-- /.col-lg-12 -->
</div>

<div class="row">
  <div class="col-lg-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-comments fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge"><%=Member.count%></div>
            <div><%=I18n.t(:current_members, scope: :dashboard)%></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <%=I18n.t(:members_dashboard, scope: :dashboard)%>
      </div>
      <div class="panel-body">
        <%= line_chart Member.group("DATE(created_at)").count, xtitle: I18n.t(:date, scope: :dashboard), ytitle: I18n.t(:new_members, scope: :dashboard) %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrapper">
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0px;">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%=root_path%>"><%=I18n.t(:member_system, scope: :generic)%></a>
      </div>
      <!-- /.navbar-header -->

      <ul class="nav navbar-top-links navbar-right">
        <!-- /.dropdown -->
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
          </a>
          <ul class="dropdown-menu dropdown-user">
            <li><a href="change_password.html"><i class="fa fa-gear fa-fw"></i><%=I18n.t(:change_password, scope: :generic)%></a></li>
            <li class="divider"></li>
            <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i><%=I18n.t(:logout, scope: :generic)%></a></li>
          </ul>
          <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
      </ul>
      <!-- /.navbar-top-links -->

      <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
          <ul class="nav in" id="side-menu">
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-dashboard fa-fw"></i><%=I18n.t(:dashboard, scope: :generic)%>
              <% end %>
            </li>
            <li>
              <%= link_to members_path do %>
                <i class="fa fa-table fa-fw"></i><%=I18n.t(:members, scope: :generic)%>
              <% end %>
            </li>
            <li>
              <%= link_to charts_path do %>
                <i class="fa fa-table fa-fw"></i><%=I18n.t(:charts, scope: :generic)%>
              <% end %>
            </li>
          </ul>
        </div>
        <!-- /.sidebar-collapse -->
      </div>
      <!-- /.navbar-static-side -->
    </nav>

    <div id="page-wrapper">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/members/import.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%=I18n.t(:import_members, scope: :members)%></h1>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <%=I18n.t(:import_members, scope: :members)%>
  </div>
  <div class="panel-body">
    <% if flash[:error] %>
      <div class="row">
        <div class="col-lg-6">
          <%= I18n.t(flash[:error], scope: :members) %>
        </div>
      </div>
    <% end %>

    <div class="row">
      <div class="col-lg-6">
        <%= form_tag preview_members_path, multipart: true do %>
          <label for="file"><%= I18n.t(:import_title, scope: :members) %></label>
          <%= file_field_tag "member_files[]", :multiple => true, :accept => '.xlsx' %>
          <p class="help-block"><%= I18n.t(:import_hint, scope: :members, val: MemberSystem::MemberFilesParser::MAX_ROWS) %></p>

          <%= submit_tag I18n.t(:import_members, scope: :members), :class => "btn btn-primary" %> 
          <%= link_to I18n.t(:cancel_member, scope: :members), members_path, :class => "btn btn-default" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/members/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%=I18n.t(:members, scope: :generic)%></h1>
  </div>
</div>

<div class="row" style="padding-bottom: 15px;">
  <div class="col-lg-12">
    <%= link_to I18n.t(:create_member, scope: :members), new_member_path, class: "btn btn-outline btn-primary btn-lg" %>
    <%= link_to I18n.t(:import_members, scope: :members), import_members_path, class: "btn btn-outline btn-primary btn-lg" %>
  </div>
</div>

<% if flash[:message] || flash[:error] %>
  <div class="row">
    <div class="col-lg-12">
      <% if flash[:message] %>
        <%= I18n.t(flash[:message].first, flash[:message].last.symbolize_keys.merge(scope: :members)) %>
      <% else %>
        <%= I18n.t(flash[:error], scope: :members) %>
      <% end %>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <%=I18n.t(:members, scope: :members)%>
      </div>
      <div class="panel-body" id="members-panel-body">
        <table id="members" class="display">
          <thead>
            <tr>
              <% MemberSystem::MemberFilesParser::COLUMNS.each do |column| %>
                <th><%= I18n.t(column, scope: :members) %></th>
              <% end %>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <% MemberSystem::MemberFilesParser::COLUMNS.each do |column| %>
                <th>
                  <input type="text" placeholder=<%= I18n.t(column, scope: :members) %> />
                </th>
              <% end %>
            </tr>
          </tfoot>
        </table>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function() {
    var table = $('#members').DataTable({
      processing: true,
      serverSide: true,
      ajax: {
        "url": "<%=list_members_path(format: :json)%>",
        "type": "POST"
      },
      responsive: true,
      dom: '<l<t>ip>',
      ordering:  false
    });

    table.on('responsive-display', function() { $("#members").css("width", "100%") });
    table.on('responsive-resize', function() { $("#members").css("width", "100%") });
    table.on('processing', function() { $("#members").css("width", "100%") });

    table.columns().every(function () {
      var that = this;
      $( 'input', this.footer() ).on( 'keyup change', function () {
        if ( that.search() !== this.value ) {
          that.search( this.value ).draw();
        }
      });
    });
  });

  $(window).load(function(){
  });
</script>

app/views/members/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%=I18n.t(:new_member, scope: :members)%></h1>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <%=I18n.t(:basic_information, scope: :members)%>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-lg-6">
        <%= semantic_form_for @member do |f| %>
          <%= f.inputs :name => I18n.t(:basic_information, scope: :members) do %>
            <%= f.input :name %>
            <%= f.input :email, :as => :email %>
            <%= f.input :age, :as => :number %>
            <%= f.input :gender, :as => :select, :collection => [[I18n.t(:male, scope: :members), :male], [I18n.t(:female, scope: :members), :female]] %>
          <% end %>

          <%= f.actions do %>
            <%= f.action :submit, :as => :button, :label => I18n.t(:create_member, scope: :members), :button_html => {:class => "btn btn-primary"} %>
            <%= f.action :cancel, :as => :link, :label => I18n.t(:cancel_member, scope: :members), :button_html => {:class => "btn btn-default"} %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/members/preview.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%=I18n.t(:preview_members, scope: :members)%></h1>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <%=I18n.t(:import_members, scope: :members)%>
      </div>
      <div class="panel-body">
        <table id="members_preview" class="display" width="100%">
          <thead>
            <tr>
              <% MemberSystem::MemberFilesParser::COLUMNS.each do |column| %>
                <th><%= I18n.t(column, scope: :members) %></th>
              <% end %>
            </tr>
          </thead>
        </table>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <%= form_tag upload_members_path, multipart: true do %>
          <% params[:member_files].map do |f| %>
            <%= hidden_field_tag "member_files[]",  f.path %>
          <% end %>

          <%= submit_tag I18n.t(:import_members, scope: :members), :class => "btn btn-primary" %> 
          <%= link_to I18n.t(:cancel_member, scope: :members), members_path, :class => "btn btn-default" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function() {
    $('#members_preview').DataTable({
      data: <%= @records.map { |r| r.values }.to_json.html_safe %>, 
      responsive: true
    });
  });
</script>